# Generated by Django 3.1 on 2020-08-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='weight',
            field=models.CharField(max_length=5),
        ),
    ]
