# Generated by Django 3.1 on 2020-08-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0002_auto_20200811_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='sell_time',
        ),
        migrations.AddField(
            model_name='sell',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
    ]
